### ISSUE TITLE
Feature Request: Option to create sitemaps of all file-types in V2

### ISSUE THREAD

**Issue by mrowell** [zerodevx/static-sitemap-cli#13]
We use static-sitemap-cli to create sitemaps of our media and non-html document assets. We don't analyse the content of these files for links. We just create a sitemap of the list of files from the source directory. 

Would it be possible to add an option to allow the creation site maps of all file types in V2? 

I totally would understand if this is outside of the scope of what you are trying to achieve with static-sitemap-cli. 

Thanks for sharing your work. 
Marcus.

**Comment by zerodevx** [comment]
Oh I see - I'll add this feature.

**Comment by zerodevx** [comment]
Hey I've added the `--match` option that'll allow you to trawl for any file types. Hope this fits your use-case. Here's a usage example: https://github.com/zerodevx/static-sitemap-cli#generate-txt-sitemap-for-image-assets

**Comment by mrowell** [comment]
@zerodevx Awesome. Thanks for implementing this for us. 

I've tested it and it all working great. 

Thank you.
Marcus.
